### ISSUE TITLE
node-red-contrib-ros-wmn Installation issue

### ISSUE THREAD

**Issue by jcotof** [openipd/node-red-contrib-ros-wnm#2]
Hello, I want to know if you can help me, I am installing **node-red-contrib-ros-wnm** on node-red from the manage palette, but it gives me the following error:

_node-red-contrib-ros-wnm
1.0.2
SyntaxError: missing ) after argument list (line:3)_

Can you help me solve it?

I would also like to know if you have more examples about publish messages in rosbridge with node-red?

**Comment by chbarrer** [comment]
Hi !.. same problem... using ROS noetic and raspOS 64 bits. Some idea?
